# Generated by Django 2.1.5 on 2019-09-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.CharField(choices=[('PO', 'Polera'), ('FA', 'Falda'), ('PN', 'Polerones'), ('VT', 'Vestidos')], default='PO', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='etiqueta',
            field=models.CharField(choices=[('P', 'primario'), ('S', 'segundario'), ('R', 'riesgo')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
