# Generated by Django 2.1.5 on 2019-09-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190919_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='slug',
            field=models.SlugField(default='test-producto'),
            preserve_default=False,
        ),
    ]
