# Generated by Django 2.1.5 on 2019-09-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_articulo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='precio_descuento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
