# Generated by Django 2.1.5 on 2019-09-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_articulo_precio_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(default='Esto es una descripcion Test'),
            preserve_default=False,
        ),
    ]
