# Generated by Django 2.1.5 on 2019-09-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_articulo_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoarticulo',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
