# Generated by Django 2.1.5 on 2019-09-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pedidoarticulo_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='pedido',
            new_name='fuepedido',
        ),
    ]
