# Generated by Django 2.1.5 on 2019-09-20 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20190920_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoarticulo',
            name='fuepedido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidoarticulo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
