# Generated by Django 2.1.5 on 2019-09-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_articulo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
